### ISSUE TITLE
BUG | do_VolcanoPlot | Label Error

### ISSUE THREAD

**Issue by brigidar** [enblacar/SCpubr#85]
**Bug:**
```
Thanks for the package. I was trying to create a volcano plot and ran into an issue with labeling. When I give the number of genes to label it counts genes that have a significant p-value, but not a significant fold change within the total numbers of genes to label despite using the order_tags_by == "both" option. I included the R code below.
Thanks a bunch.
```

**Reproducible example:**
```r
v4 <- SCpubr::do_VolcanoPlot(sample = experiment.clusters,
                            de_genes = markers.ent4,n_genes=10,pt.size=1 )
```

**SCpubr version:**
```r
v 2.0.2
```

**Session info:**
```r
R version 4.4.0 (2024-04-24)
Platform: x86_64-apple-darwin20
Running under: macOS Ventura 13.7.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] SCpubr_2.0.2                rlist_0.4.6.2              
 [3] cowplot_1.1.3               RColorBrewer_1.1-3         
 [5] scCDC_1.4                   tidyr_1.3.1                
 [7] knitr_1.49                  pROC_1.18.5                
 [9] Matrix_1.7-1                pbapply_1.7-2              
[11] ddpcr_1.15.2                SeuratExtend_1.1.4         
[13] SeuratExtendData_0.2.1      extrafont_0.19             
[15] ComplexHeatmap_2.20.0       colorspace_2.1-1           
[17] gridExtra_2.3               CellChat_2.1.2             
[19] igraph_2.1.4                ggrepel_0.9.6              
[21] forcats_1.0.0               scales_1.3.0               
[23] alphonse_0.0.1.0            biomaRt_2.60.1             
[25] gprofiler2_0.2.3            tradeSeq_1.18.0            
[27] slingshot_2.12.0            TrajectoryUtils_1.12.0     
[29] SingleCellExperiment_1.26.0 SummarizedExperiment_1.34.0
[31] Biobase_2.64.0              GenomicRanges_1.56.2       
[33] GenomeInfoDb_1.40.1         IRanges_2.38.1             
[35] S4Vectors_0.42.1            BiocGenerics_0.50.0        
[37] MatrixGenerics_1.16.0       matrixStats_1.5.0          
[39] princurve_2.1.6             scCustomize_3.0.1          
[41] viridis_0.6.5               viridisLite_0.4.2          
[43] patchwork_1.3.0             SeuratWrappers_0.3.5       
[45] Seurat.utils_2.8.0          magrittr_2.0.3             
[47] ggExpress_0.9.0             MarkdownHelpers_1.0.7      
[49] ggpubr_0.6.0                CodeAndRoll2_2.6.0         
[51] Stringendo_0.6.0            clustree_0.5.1             
[53] ggraph_2.2.1                ggplot2_3.5.1              
[55] dplyr_1.1.4                 Seurat_5.2.1               
[57] SeuratObject_5.0.2          sp_2.2-0                   

loaded via a namespace (and not attached):
  [1] ica_1.0-3                plotly_4.10.4            Formula_1.2-5           
  [4] rematch2_2.1.2           zlibbioc_1.50.0          tidyselect_1.2.1        
  [7] bit_4.5.0.1              doParallel_1.0.17        clue_0.3-66             
 [10] lattice_0.22-6           rjson_0.2.23             EnhancedVolcano_1.22.0  
 [13] blob_1.2.4               stringr_1.5.1            rngtools_1.5.2          
 [16] S4Arrays_1.4.1           tictoc_1.2.1             parallel_4.4.0          
 [19] png_0.1-8                cli_3.6.4                ggplotify_0.1.2         
 [22] registry_0.5-1           goftest_1.2-3            textshaping_0.4.1       
 [25] purrr_1.0.4              ggnetwork_0.5.13         BiocNeighbors_1.22.0    
 [28] uwot_0.2.2               shadowtext_0.1.4         curl_6.2.0              
 [31] mime_0.12                evaluate_1.0.3           tidytree_0.4.6          
 [34] stringi_1.8.4            backports_1.5.0          lubridate_1.9.4         
 [37] ggVennDiagram_1.5.2      httpuv_1.6.15            AnnotationDbi_1.66.0    
 [40] paletteer_1.6.0          clusterProfiler_4.12.6   rappdirs_0.3.3          
 [43] splines_4.4.0            RApiSerialize_0.1.4      sctransform_0.4.1       
 [46] ggbeeswarm_0.7.2         sessioninfo_1.2.2        SoupX_1.6.2             
 [49] DBI_1.2.3                jquerylib_0.1.4          withr_3.0.2             
 [52] systemfonts_1.1.0        enrichplot_1.24.4        lmtest_0.9-40           
 [55] tidygraph_1.3.1          formatR_1.14             BiocManager_1.30.25     
 [58] htmlwidgets_1.6.4        fs_1.6.5                 tidyverse_2.0.0         
 [61] statnet.common_4.10.0    labeling_0.4.3           SparseArray_1.4.8       
 [64] reticulate_1.40.0        zoo_1.8-12               XVector_0.44.0          
 [67] network_1.19.0           UCSC.utils_1.0.0         timechange_0.3.0        
 [70] foreach_1.5.2            caTools_1.18.3           data.table_1.16.4       
 [73] ggtree_3.12.0            R.oo_1.27.0              RSpectra_0.16-2         
 [76] irlba_2.3.5.1            extrafontdb_1.0          clipr_0.8.0             
 [79] ggrastr_1.0.2            fastDummies_1.7.5        gridGraphics_0.5-1      
 [82] lazyeval_0.2.2           yaml_2.3.10              survival_3.8-3          
 [85] scattermore_1.2          crayon_1.5.3             RcppAnnoy_0.0.22        
 [88] progressr_0.15.1         tweenr_2.0.3             later_1.4.1             
 [91] ggridges_0.5.6           codetools_0.2-20         GlobalOptions_0.1.2     
 [94] KEGGREST_1.44.1          Rtsne_0.17               shape_1.4.6.1           
 [97] limma_3.60.6             filelock_1.0.3           splitstackshape_1.4.8   
[100] pkgconfig_2.0.3          xml2_1.3.6               spatstat.univar_3.1-1   
[103] aplot_0.2.4              spatstat.sparse_3.1-0    ape_5.8-1               
[106] gridBase_0.4-7           xtable_1.8-4             car_3.1-3               
[109] plyr_1.8.9               httr_1.4.7               tools_4.4.0             
[112] globals_0.16.3           beeswarm_0.4.0           broom_1.0.7             
[115] checkmate_2.3.2          nlme_3.1-166             futile.logger_1.4.3     
[118] lambda.r_1.2.4           dbplyr_2.5.0             assertthat_0.2.1        
[121] digest_0.6.37            farver_2.1.2             tzdb_0.4.0              
[124] reshape2_1.4.4           yulab.utils_0.1.8        glue_1.8.0              
[127] cachem_1.1.0             VennDiagram_1.7.3        BiocFileCache_2.12.0    
[130] polyclip_1.10-7          generics_0.1.3           Biostrings_2.72.1       
[133] ggalluvial_0.12.5        presto_1.0.0             parallelly_1.42.0       
[136] statmod_1.5.0            ragg_1.3.3               RcppHNSW_0.6.0          
[139] carData_3.0-5            httr2_1.0.7              job_0.3.1               
[142] spam_2.11-1              vroom_1.6.5              gson_0.1.0              
[145] graphlayouts_1.2.1       gtools_3.9.5             ggsignif_0.6.4          
[148] shiny_1.10.0             GenomeInfoDbData_1.2.12  R.utils_2.12.3          
[151] memoise_2.0.1            rmarkdown_2.29           pheatmap_1.0.12         
[154] R.methodsS3_1.8.2        svglite_2.1.3            future_1.34.0           
[157] RANN_2.6.2               stringfish_0.16.0        spatstat.data_3.1-4     
[160] rstudioapi_0.17.1        cluster_2.1.8            janitor_2.2.1           
[163] spatstat.utils_3.1-2     hms_1.1.3                fitdistrplus_1.2-2      
[166] munsell_0.5.1            vioplot_0.5.0            ggcorrplot_0.1.4.1      
[169] FNN_1.1.4.1              rlang_1.1.5              HGNChelper_0.8.15       
[172] sparseMatrixStats_1.16.0 dotCall64_1.2            ggforce_0.4.2           
[175] circlize_0.4.16          mgcv_1.9-1               xfun_0.50               
[178] coda_0.19-4.1            sna_2.8                  remotes_2.5.0           
[181] iterators_1.0.14         abind_1.4-8              GOSemSim_2.30.2         
[184] tibble_3.2.1             treeio_1.28.0            DatabaseLinke.R_1.7.0   
[187] readr_2.1.5              futile.options_1.0.1     bitops_1.0-9            
[190] promises_1.3.2           scatterpie_0.2.4         RSQLite_2.3.9           
[193] qvalue_2.36.0            openxlsx_4.2.7.1         fgsea_1.30.0            
[196] DelayedArray_0.30.1      ReadWriter_1.5.4         GO.db_3.19.1            
[199] compiler_4.4.0           colorRamps_2.3.4         prettyunits_1.2.0       
[202] listenv_0.9.1            Rcpp_1.0.14              Rttf2pt1_1.3.12         
[205] edgeR_4.2.2              tensor_1.5               qs_0.27.2               
[208] MASS_7.3-64              progress_1.2.3           BiocParallel_1.38.0     
[211] spatstat.random_3.3-2    R6_2.6.0                 fastmap_1.2.0           
[214] fastmatch_1.1-6          rstatix_0.7.2            vipor_0.4.7             
[217] ROCR_1.0-11              rsvd_1.0.5               gtable_0.3.6            
[220] KernSmooth_2.23-26       miniUI_0.1.1.1           deldir_2.0-4            
[223] htmltools_0.5.8.1        RcppParallel_5.1.9       bit64_4.6.0-1           
[226] spatstat.explore_3.3-4   lifecycle_1.0.4          ggprism_1.0.5           
[229] zip_2.3.1                MarkdownReports_4.7.1    sass_0.4.9              
[232] vctrs_0.6.5              sm_2.2-6.0               spatstat.geom_3.3-5     
[235] snakecase_0.11.1         DOSE_3.30.5              NMF_0.28                
[238] ggfun_0.1.8              future.apply_1.11.3      bslib_0.9.0             
[241] pillar_1.10.1            gplots_3.2.0             locfit_1.5-9.10         
[244] jsonlite_1.8.9           GetoptLong_1.0.5  
```

**Comment by enblacar** [comment]
Hi @brigidar,

Thanks for using my package!

Indeed, I also noticed this bug. It should be already fixed in the recent commits and it is set up to release with the next `SCpubr` version! :). If you decide to download the latest commits, be aware that it will be an unstable version, as I am currently working on a transitioning to v3.0.0.

Thanks for opening the Issue, and feel free to do it again should you encounter any more errors!

Have a good day!
Enrique

**Comment by brigidar** [comment]
Hi Enrique,
I tried to pull your latest version with the following command remotes::install_github("enblacar/SCpubr@1eb179b") but when I run the do_VolcanoPlot with the n_genes=10 I still get duplicated names and also I get genes that are less than the log2FC cutoff labeled. I am supposed to get it a different way?
Brigida

**Comment by enblacar** [comment]
Hi @brigidar,

Thanks for reaching out! Interestingly, I do not seem to be able to reproduce the problem. With my test dataset, I get the expected result with:

```r
SCpubr::do_VolcanoPlot(sample = sample, de_genes, n_genes = 10)
```

![Image](https://github.com/user-attachments/assets/e942122e-01a4-47a1-a5b0-dd49114974f8)

As you can see, the labels are not duplicated and the thresholds seem to applied as they should.


To debug this further, do you think it would be possible for you to send me the DE genes RDS object to scpubr@gmail.com and post again the exact code you are using? Please make sure to remove any data that might be confidential.  This would help me greatly to solve this issue.

Thanks again for your interest in `SCpubr`! I will come back to you as soon as I find out the root of the Issue.

Best,
Enrique

**Comment by brigidar** [comment]
I only observe the duplication when there are less than 10 genes on one side. I have some conditions where there is almost no upregulation and only down regulation and then I get the duplication. I will work on setting up a small RDS object that I can send you to replicate the phenomenon.

**Comment by enblacar** [comment]
HI @brigidar 

I just wanted to check back on you regarding this issue. `SCpubr` v3.0.0 is no on CRAN! Would it be possible for you to update it and check if your error still persists there?

Best,
Enrique
